Feat/create mkdocs documentation
gisaia/ARLAS-Exploration-stack pull request #144
Opened 2024-12-17 14:32 UTC by WilliGautier

2024-12-17 15:46 UTC, sylvaingaudan requested changes

2024-12-17 15:46 UTC, sylvaingaudan commented on scripts/release.sh
> +git add docs/docs/dc_services/docker_compose_services_*.md
this is not the same as listing the files: some are intentionnaly missing.

2024-12-17 15:46 UTC, sylvaingaudan commented on scripts/release.sh
> +mkdocs gh-deploy -f docs/mkdocs.yml
this is not the same as listing the files: some are intentionnaly missing.

2024-12-17 15:46 UTC, sylvaingaudan commented on scripts/release.sh
> +./mkDocs.sh
this is not the same as listing the files: some are intentionnaly missing.

2024-12-17 16:34 UTC, QuCMGisaia approved these changes

2024-12-18 08:03 UTC, MohamedHamouGisaia reviewed
LGTM, a part from the generated docker-composes services markdown files, (@sylvaingaudan's comments)

2024-12-18 08:21 UTC, WilliGautier commented on scripts/release.sh
> +./mkDocs.sh
I don't understand what you mean by 'listing the files".
I didn't change those lines, I just moved it into `./mkDocs.sh`

2024-12-18 08:35 UTC, sylvaingaudan approved these changes

2024-12-18 08:37 UTC, merged